from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from typing import List
import io

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from ..database import get_db
from ..models import db_models, schemas
from .auth import get_current_user
from ..services.websocket_manager import manager

router = APIRouter(prefix="/inquiry", tags=["inquiry"])

ASPHALT = HexColor("#1B1F23")
AMBER = HexColor("#E8862A")
MUTED = HexColor("#6b7280")
BORDER = HexColor("#e5e7eb")
LIGHT_BG = HexColor("#f8f6f2")


def format_inr(amount: float) -> str:
    if amount >= 100000:
        lakhs = amount / 100000
        return f"\u20b9{lakhs:,.2f}L"
    whole = int(amount)
    s = str(whole)
    if len(s) > 3:
        last3 = s[-3:]
        rest = s[:-3]
        parts = []
        while len(rest) > 2:
            parts.append(rest[-2:])
            rest = rest[:-2]
        parts.append(rest)
        parts.reverse()
        formatted = ",".join(parts) + "," + last3
    else:
        formatted = s
    return f"\u20b9{formatted}"


def build_spec_sheet_pdf(car: db_models.Car) -> io.BytesIO:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm,
                             leftMargin=20 * mm, rightMargin=20 * mm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("Title", parent=styles["Title"], fontSize=22, textColor=ASPHALT, spaceAfter=2)
    subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"], fontSize=10, textColor=MUTED, spaceAfter=10)
    heading_style = ParagraphStyle("Heading", parent=styles["Normal"], fontSize=12, fontName="Helvetica-Bold",
                                    textColor=ASPHALT, spaceBefore=14, spaceAfter=6)
    price_style = ParagraphStyle("Price", parent=styles["Title"], fontSize=20, textColor=AMBER, spaceAfter=10)

    elements = []
    elements.append(Paragraph("AutoWave — Vehicle Spec Sheet", subtitle_style))
    elements.append(Paragraph(car.title, title_style))
    elements.append(Paragraph(format_inr(car.price), price_style))

    elements.append(Paragraph("Specifications", heading_style))
    spec_rows = [
        ["Make", car.make, "Model", car.model],
        ["Year", str(car.year), "Body Type", car.body_type.value.title()],
        ["Mileage", f"{car.mileage:,} km", "Fuel Type", car.fuel_type.value.title()],
        ["Transmission", car.transmission.value.title(), "Condition", car.condition.value.replace("_", " ").title()],
        ["Color", car.color or "—", "Location", car.location or "—"],
    ]
    table = Table(spec_rows, colWidths=[35 * mm, 55 * mm, 35 * mm, 55 * mm])
    table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), MUTED),
        ("TEXTCOLOR", (2, 0), (2, -1), MUTED),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("LINEBELOW", (0, 0), (-1, -2), 0.5, BORDER),
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
    ]))
    elements.append(table)

    if car.description:
        elements.append(Paragraph("Description", heading_style))
        elements.append(Paragraph(car.description, styles["Normal"]))

    elements.append(Spacer(1, 16))
    elements.append(Paragraph(f"Listing ID: #{car.id} — Generated by AutoWave", subtitle_style))

    doc.build(elements)
    buf.seek(0)
    return buf


@router.post("/", response_model=schemas.InquiryResponse)
async def create_inquiry(
    payload: schemas.InquiryCreate,
    db: AsyncSession = Depends(get_db),
    user: db_models.User = Depends(get_current_user),
):
    car_result = await db.execute(select(db_models.Car).where(db_models.Car.id == payload.car_id))
    car = car_result.scalars().first()
    if not car:
        raise HTTPException(status_code=404, detail="Car not found")

    inquiry = db_models.Inquiry(
        user_id=user.id, car_id=payload.car_id, message=payload.message, phone=payload.phone
    )
    db.add(inquiry)
    db.add(db_models.Event(user_id=user.id, car_id=payload.car_id, event_type=db_models.EventType.INQUIRY))
    await db.commit()
    await db.refresh(inquiry)

    await manager.broadcast({"type": "new_inquiry", "car_id": car.id, "seller_id": car.seller_id})
    return inquiry


@router.get("/my-inquiries", response_model=List[schemas.InquiryResponse])
async def my_inquiries(
    db: AsyncSession = Depends(get_db),
    user: db_models.User = Depends(get_current_user),
):
    result = await db.execute(
        select(db_models.Inquiry)
        .where(db_models.Inquiry.user_id == user.id)
        .order_by(db_models.Inquiry.created_at.desc())
    )
    return result.scalars().all()


@router.get("/received", response_model=List[schemas.InquiryResponse])
async def received_inquiries(
    db: AsyncSession = Depends(get_db),
    user: db_models.User = Depends(get_current_user),
):
    """Inquiries buyers sent about cars this user is selling."""
    result = await db.execute(
        select(db_models.Inquiry)
        .join(db_models.Car, db_models.Inquiry.car_id == db_models.Car.id)
        .where(db_models.Car.seller_id == user.id)
        .order_by(db_models.Inquiry.created_at.desc())
    )
    return result.scalars().all()


@router.get("/spec-sheet/{car_id}")
async def download_spec_sheet(car_id: int, db: AsyncSession = Depends(get_db)):
    result = await db.execute(select(db_models.Car).where(db_models.Car.id == car_id))
    car = result.scalars().first()
    if not car:
        raise HTTPException(status_code=404, detail="Car not found")

    pdf_buf = build_spec_sheet_pdf(car)
    filename = f"spec_sheet_car_{car.id}.pdf"
    return StreamingResponse(
        pdf_buf,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )
